### ISSUE TITLE
Fails to compile on ghc 9.2.1

### ISSUE THREAD

**Issue by emberdart** [0xd34df00d/inline-asm#3]
I am getting the following when compiling with ghc 9.2.1:
```
[4 of 5] Compiling Language.Asm.Inline ( src/Language/Asm/Inline.hs, dist/build/Language/Asm/Inline.o, dist/build/Language/Asm/Inline.dyn_o )

src/Language/Asm/Inline.hs:48:19: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int8#’
    • In the expression: w
      In an equation for ‘unbox’: unbox (I8# w) = w
      In the instance declaration for ‘AsmArg Int8 'IntRep Int#’
   |
48 |   unbox (I8# w) = w
   |                   ^

src/Language/Asm/Inline.hs:49:11: error:
    • Couldn't match type ‘Int8#’ with ‘Int#’
      Expected: Int# -> Int8
        Actual: Int8# -> Int8
    • In the expression: I8#
      In an equation for ‘rebox’: rebox = I8#
      In the instance declaration for ‘AsmArg Int8 'IntRep Int#’
   |
49 |   rebox = I8#
   |           ^^^

src/Language/Asm/Inline.hs:52:20: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int16#’
    • In the expression: w
      In an equation for ‘unbox’: unbox (I16# w) = w
      In the instance declaration for ‘AsmArg Int16 'IntRep Int#’
   |
52 |   unbox (I16# w) = w
   |                    ^

src/Language/Asm/Inline.hs:53:11: error:
    • Couldn't match type ‘Int16#’ with ‘Int#’
      Expected: Int# -> Int16
        Actual: Int16# -> Int16
    • In the expression: I16#
      In an equation for ‘rebox’: rebox = I16#
      In the instance declaration for ‘AsmArg Int16 'IntRep Int#’
   |
53 |   rebox = I16#
   |           ^^^^

src/Language/Asm/Inline.hs:56:20: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int32#’
    • In the expression: w
      In an equation for ‘unbox’: unbox (I32# w) = w
      In the instance declaration for ‘AsmArg Int32 'IntRep Int#’
   |
56 |   unbox (I32# w) = w
   |                    ^

src/Language/Asm/Inline.hs:57:11: error:
    • Couldn't match type ‘Int32#’ with ‘Int#’
      Expected: Int# -> Int32
        Actual: Int32# -> Int32
    • In the expression: I32#
      In an equation for ‘rebox’: rebox = I32#
      In the instance declaration for ‘AsmArg Int32 'IntRep Int#’
   |
57 |   rebox = I32#
   |           ^^^^

src/Language/Asm/Inline.hs:72:19: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the expression: w
      In an equation for ‘unbox’: unbox (W8# w) = w
      In the instance declaration for ‘AsmArg Word8 'WordRep Word#’
   |
72 |   unbox (W8# w) = w
   |                   ^

src/Language/Asm/Inline.hs:73:11: error:
    • Couldn't match type ‘Word8#’ with ‘Word#’
      Expected: Word# -> Word8
        Actual: Word8# -> Word8
    • In the expression: W8#
      In an equation for ‘rebox’: rebox = W8#
      In the instance declaration for ‘AsmArg Word8 'WordRep Word#’
   |
73 |   rebox = W8#
   |           ^^^

src/Language/Asm/Inline.hs:76:20: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word16#’
    • In the expression: w
      In an equation for ‘unbox’: unbox (W16# w) = w
      In the instance declaration for ‘AsmArg Word16 'WordRep Word#’
   |
76 |   unbox (W16# w) = w
   |                    ^

src/Language/Asm/Inline.hs:77:11: error:
    • Couldn't match type ‘Word16#’ with ‘Word#’
      Expected: Word# -> Word16
        Actual: Word16# -> Word16
    • In the expression: W16#
      In an equation for ‘rebox’: rebox = W16#
      In the instance declaration for ‘AsmArg Word16 'WordRep Word#’
   |
77 |   rebox = W16#
   |           ^^^^

src/Language/Asm/Inline.hs:80:20: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word32#’
    • In the expression: w
      In an equation for ‘unbox’: unbox (W32# w) = w
      In the instance declaration for ‘AsmArg Word32 'WordRep Word#’
   |
80 |   unbox (W32# w) = w
   |                    ^

src/Language/Asm/Inline.hs:81:11: error:
    • Couldn't match type ‘Word32#’ with ‘Word#’
      Expected: Word# -> Word32
        Actual: Word32# -> Word32
    • In the expression: W32#
      In an equation for ‘rebox’: rebox = W32#
      In the instance declaration for ‘AsmArg Word32 'WordRep Word#’
   |
81 |   rebox = W32#
   |           ^^^^

src/Language/Asm/Inline.hs:148:12: error:
    • Couldn't match expected type: TyVarBndr Specificity
                  with actual type: flag1 -> TyVarBndr flag1
    • Probable cause: ‘PlainTV’ is applied to too few arguments
      In the expression: PlainTV m
      In the first argument of ‘ForallT’, namely ‘[PlainTV m]’
      In the first argument of ‘(<$>)’, namely
        ‘ForallT [PlainTV m] [AppT (ConT ''PrimMonad) (VarT m)]’
    |
148 |   ForallT [PlainTV m] [AppT (ConT ''PrimMonad) (VarT m)] <$> go m ty
    |            ^^^^^^^^^

src/Language/Asm/Inline.hs:159:12: error:
    • Couldn't match expected type: TyVarBndr Specificity
                  with actual type: flag0 -> TyVarBndr flag0
    • Probable cause: ‘PlainTV’ is applied to too few arguments
      In the expression: PlainTV s
      In the first argument of ‘ForallT’, namely ‘[PlainTV s]’
      In the first argument of ‘(<$>)’, namely ‘ForallT [PlainTV s] []’
    |
159 |   ForallT [PlainTV s] [] <$> go s ty
    |    
```
Is there any way of fixing this and/or overriding?

Some of it's the Word proposal, other bits are the TH changes recently that might want to be CPP'd.

Thanks

**Comment by 0xd34df00d** [comment]
I'd be absolutely happy to fix this!

To save some time for me, how are you building with ghc 9.2.1? Last time I tried doing that for a different project while still trying to rely on `stack`, it turned out to be a mess.

**Comment by emberdart** [comment]
I'm just doing it via Nix (at the moment, master).

**Comment by 0xd34df00d** [comment]
Took a bit to figure nix out to test with ghc 9.2, but it should be good now. Thanks for the report!
