### ISSUE TITLE
Fails to compile on ghc 9.4

### ISSUE THREAD

**Issue by emberdart** [0xd34df00d/inline-asm#4]
Hello, attempting to compile using 9.4 gives me:

```
src/Language/Asm/Inline.hs:80:20: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int64#’
    • In the expression: w
      In an equation for ‘unbox’: unbox (I64# w) = w
      In the instance declaration for ‘AsmArg Int64 Int#’
   |
80 |   unbox (I64# w) = w
   |                    ^

src/Language/Asm/Inline.hs:81:11: error:
    • Couldn't match type ‘Int64#’ with ‘Int#’
      Expected: Int# -> Int64
        Actual: Int64# -> Int64
    • In the expression: I64#
      In an equation for ‘rebox’: rebox = I64#
      In the instance declaration for ‘AsmArg Int64 Int#’
   |
81 |   rebox = I64#
   |           ^^^^

src/Language/Asm/Inline.hs:104:20: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word64#’
    • In the expression: w
      In an equation for ‘unbox’: unbox (W64# w) = w
      In the instance declaration for ‘AsmArg Word64 Word#’
    |
104 |   unbox (W64# w) = w
    |                    ^

src/Language/Asm/Inline.hs:105:11: error:
    • Couldn't match type ‘Word64#’ with ‘Word#’
      Expected: Word# -> Word64
        Actual: Word64# -> Word64
    • In the expression: W64#
      In an equation for ‘rebox’: rebox = W64#
      In the instance declaration for ‘AsmArg Word64 Word#’
    |
105 |   rebox = W64#
    |           ^^^^
[5 of 5] Compiling Paths_inline_asm ( dist/build/autogen/Paths_inline_asm.hs, dist/build/Paths_inline_asm.o, dist/build/Paths_inline_asm.dyn_o )
error: builder for '/nix/store/gc92b4br3bz50l37ajlmlj5hl2x261vk-inline-asm-0.5.0.1.drv' failed with exit code 1;
       last 10 log lines:
       >     • Couldn't match type ‘Word64#’ with ‘Word#’
       >       Expected: Word# -> Word64
       >         Actual: Word64# -> Word64
       >     • In the expression: W64#
       >       In an equation for ‘rebox’: rebox = W64#
       >       In the instance declaration for ‘AsmArg Word64 Word#’
       >     |
       > 105 |   rebox = W64#
       >     |           ^^^^
       > [5 of 5] Compiling Paths_inline_asm ( dist/build/autogen/Paths_inline_asm.hs, dist/build/Paths_inline_asm.o, dist/build/Paths_inline_asm.dyn_o )
```

Is this something that's addable with CPP?

Thanks

**Comment by 0xd34df00d** [comment]
Sorry for the long wait — this should be fixed in `HEAD` (in b75204581916caae8f8d7048b9f8ffba0623ed67 to be precise). Let me know if it works for you, and I'll make a release with ghc 9.4 compatibility.

**Comment by emberdart** [comment]
Thanks, that seems to compile great!
